apiVersion: v1
kind: ReplicationController
metadata:
  name: alpine-zookeeper
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: alpine-zookeeper
    spec:
      containers:
        - name: alpine-zookeeper
          image: registry.cn-shenzhen.aliyuncs.com/sjroom/alpine-zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-zookeeper
spec:
  type: NodePort
  ports:
    - port: 2181
      protocol: TCP
      nodePort: 30004
  selector:
        name: alpine-zookeeper  