apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: registry.cn-shenzhen.aliyuncs.com/sjroom/alpine-zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: NodePort
  ports:
    - port: 2181
      nodePort: 2181
  selector:
        name: zookeeper
# https://raw.githubusercontent.com/zw23534572/alpine-zookeeper/master/k8s.yaml
# --service-node-port-range=1-65535
# docker run --name zookeeper -p 2181:2181 -d registry.cn-shenzhen.aliyuncs.com/sjroom/alpine-zookeeper